name: TNT-Survival
main: com.senpai.tntsurvival.Main
version: 1.0
api-version: 1.13
commands:
   who:
      description: Zeigt wer dieses Plugin entwickelt hat
      usage: /who
   stnt:
      description: Spawnt TNT bei jedem Spieler auf dem Server
      usage: /stnt
   tntrain:
      description: Startet den TNT Rain
      usage: /tntrain on/off